---
version: 2
plan:
  project-key: BTAF
  key: FRONTEND
  name: Btaf Swap Frontend
stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Default Job
Default Job:
  key: JOB1
  tasks:
    - checkout:
        force-clean-build: 'false'
        description: Checkout Default Repository
    - script:
        interpreter: SHELL
        scripts:
          - echo PLAN_NAME="$( echo '${bamboo.planKey}' | tr '[:upper:]' '[:lower:]')" > variables
        description: Set ENV Variable
    - inject-variables:
        file: variables
        scope: RESULT
        namespace: inject
        description: Inject Variable
    - ssh:
        host: 52.73.230.218
        port: 22
        command: 'cd /home/ubuntu/btaf-frontend/repo/btaf-swap-frontend && docker build . -t ${bamboo.inject.PLAN_NAME}:${bamboo.buildNumber}'
        authentication:
          username: ubuntu
          shared-credentials: ID_AWS  
  artifact-subscriptions: []
branches:
  create: manually
  delete:
    after-deleted-days: 1
    after-inactive-days: never
  link-to-jira: true
notifications:
  - events:
      - plan-responsibility-changed
    recipients:
      - responsible
  - events:
      - job-error
    recipients:
      - responsible
      - committers
      - watchers
  - events:
      - plan-completed
    recipients:
      - committers
      - watchers
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []
other:
  concurrent-build-plugin: system-default
  all-other-apps:
    custom:
      buildNumber.enableSyncBranchBuildNumber: 'true'
      buildExpiryConfig.enabled: 'false'
      queue.priority: DEFAULT
---
version: 2
plan:
  key: BTAF-FRONTEND
plan-permissions:
  - users:
      - nick
    permissions:
      - view
      - edit
      - build
      - clone
      - admin
  - groups:
      - TFW DevOps
      - the-fast-way-pm
    permissions:
      - view
      - edit
      - build
      - clone
      - admin
  - groups:
      - TFW Frontend Devs
    permissions:
      - view
      - edit
      - build
      - clone
---
version: 2
deployment:
  name: Btaf Swap Frontend Deployment
  source-plan: BTAF-FRONTEND
release-naming:
  next-version-name: release-192
  applies-to-branches: false
  auto-increment: true
  auto-increment-variables: []
environments:
  - Production server
Production Server:
  triggers:
    - build-success
  tasks:
    - clean
    - script:
        interpreter: SHELL
        scripts:
          - echo PLAN_NAME="$( echo '${bamboo.planKey}' | tr '[:upper:]' '[:lower:]')" > variables
    - inject-variables:
        file: variables
        scope: LOCAL
        namespace: inject
    - ssh:
        host: 52.73.230.218
        port: 22
        command: 'source ~/.profile && source ~/.bash_profile && cd /home/ubuntu/btaf-frontend && sed -i "s/image: ${bamboo.inject.PLAN_NAME}:[a-zA-Z0-9!@#|,.<>/?-]*/image: ${bamboo.inject.PLAN_NAME}:${bamboo.buildNumber}/g" docker-compose.yaml  && docker-compose up -d frontend'
        authentication:
          username: ubuntu
          shared-credentials: ID_AWS
  final-tasks: []
  variables: {}
  requirements: []
  notifications: []
---
version: 2
deployment:
  name: Btaf Swap Frontend Deployment
deployment-permissions:
  - users:
      - nick
    permissions:
      - view
      - edit
environment-permissions:
  - Development Server:
      - users:
          - nick
        permissions:
          - view
          - edit
          - deploy
      - groups:
          - TFW DevOps
          - the-fast-way-pm
          - TFW Frontend Devs
        permissions:
          - view
          - edit
          - deploy
